const BUILD = '41391ea1a4';
// Offline support: cache every file listed in precache.json, then serve cache-first.
// precache.json is regenerated by tools/build.py, which also changes its version so devices refresh.
const PREFIX = 'tummo-';

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const res = await fetch('precache.json', { cache: 'no-store' });
    const { version, files } = await res.json();
    const cache = await caches.open(PREFIX + version);
    await cache.addAll(files.map((f) => new Request(f, { cache: 'reload' })));
    self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const res = await fetch('precache.json', { cache: 'no-store' }).catch(() => null);
    const keep = res ? PREFIX + (await res.json()).version : null;
    const names = await caches.keys();
    await Promise.all(names.filter((n) => n.startsWith(PREFIX) && n !== keep).map((n) => caches.delete(n)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  event.respondWith((async () => {
    const hit = await caches.match(event.request, { ignoreSearch: true });
    if (hit) return hit;
    try { return await fetch(event.request); }
    catch (e) { return (await caches.match('index.html')) || Response.error(); }
  })());
});
